export const ROLES = [
  {
    label: "Backdoor Admin",
    value: "BACKDOOR_ADMIN",
  },
  {
    label: "User",
    value: "USER",
  },
  {
    label: "Cafeteria Staff",
    value: "C_STAFF",
  },
];

export const GRADE_LEVEL = ["11", "12"];

export const STRANDS = ["ABM", "STEM", "HUMSS", "HE", "ICT"];

export const SECTION = [
  {
    strand: "ABM",
    grade_level: "11",
    sections: [
      "SECTION 1",
      "SECTION 2",
      "SECTION 3",
      "SECTION 4",
      "SECTION 5",
      "SECTION 6",
      "SECTION 7",
      "SECTION 8",
      "SECTION 9",
      "SECTION 10",
    ],
  },
  {
    strand: "ABM",
    grade_level: "12",
    sections: [
      "SECTION 1",
      "SECTION 2",
      "SECTION 3",
      "SECTION 4",
      "SECTION 5",
      "SECTION 6",
      "SECTION 7",
      "SECTION 8",
      "SECTION 9",
      "SECTION 10",
    ],
  },
  {
    strand: "STEM",
    grade_level: "11",
    sections: [
      "SECTION 1",
      "SECTION 2",
      "SECTION 3",
      "SECTION 4",
      "SECTION 5",
      "SECTION 6",
      "SECTION 7",
      "SECTION 8",
      "SECTION 9",
      "SECTION 10",
    ],
  },
  {
    strand: "STEM",
    grade_level: "12",
    sections: [
      "SECTION 1",
      "SECTION 2",
      "SECTION 3",
      "SECTION 4",
      "SECTION 5",
      "SECTION 6",
      "SECTION 7",
      "SECTION 8",
      "SECTION 9",
      "SECTION 10",
    ],
  },
  {
    strand: "HUMSS",
    grade_level: "11",
    sections: [
      "SECTION 1",
      "SECTION 2",
      "SECTION 3",
      "SECTION 4",
      "SECTION 5",
      "SECTION 6",
      "SECTION 7",
      "SECTION 8",
      "SECTION 9",
      "SECTION 10",
    ],
  },
  {
    strand: "HUMSS",
    grade_level: "12",
    sections: [
      "SECTION 1",
      "SECTION 2",
      "SECTION 3",
      "SECTION 4",
      "SECTION 5",
      "SECTION 6",
      "SECTION 7",
      "SECTION 8",
      "SECTION 9",
      "SECTION 10",
    ],
  },
  {
    strand: "HE",
    grade_level: "11",
    sections: [
      "SECTION 1",
      "SECTION 2",
      "SECTION 3",
      "SECTION 4",
      "SECTION 5",
      "SECTION 6",
      "SECTION 7",
      "SECTION 8",
      "SECTION 9",
      "SECTION 10",
    ],
  },
  {
    strand: "HE",
    grade_level: "12",
    sections: [
      "SECTION 1",
      "SECTION 2",
      "SECTION 3",
      "SECTION 4",
      "SECTION 5",
      "SECTION 6",
      "SECTION 7",
      "SECTION 8",
      "SECTION 9",
      "SECTION 10",
    ],
  },
  {
    strand: "ICT",
    grade_level: "11",
    sections: [
      "SECTION 1",
      "SECTION 2",
      "SECTION 3",
      "SECTION 4",
      "SECTION 5",
      "SECTION 6",
      "SECTION 7",
      "SECTION 8",
      "SECTION 9",
      "SECTION 10",
    ],
  },
  {
    strand: "ICT",
    grade_level: "12",
    sections: [
      "SECTION 1",
      "SECTION 2",
      "SECTION 3",
      "SECTION 4",
      "SECTION 5",
      "SECTION 6",
      "SECTION 7",
      "SECTION 8",
      "SECTION 9",
      "SECTION 10",
    ],
  },
];
